### PR TITLE
Guice: Eager Singleton vs (Lazy) Singleton

### PR DESCRIPTION
**Pull request by kristiyanpetkov**
In my PR i made a task, which shows the difference between Singleton and Eager Singleton.
The difference between both is that when binding interface to implementation as eager Singleton `bind(Factory.class).to(CarFactory.class).asEagerSingleton();` , the instance of CarFactory is being made immediately after the app is booted, while when binding as Singleton `    bind(Restaurant.class).to(ChineeseRestaurant.class).in(Singleton.class);` the instance of ChineeseRestaurant is beeing made, only when requested.

MammalProvider
screenshot from 2016-07-11 11-53-54

Binding:
screenshot from 2016-07-11 11-50-20

Demo:
screenshot from 2016-07-11 11-50-11

Output:
screenshot from 2016-07-11 11-49-56

Singletons can be used with anotations too. Example:
screenshot from 2016-07-13 17-33-34

### CODE REVIEW

**Comment by mlesikov** [comment]
it would be better if you provide us screenshot from the application execution result

**Comment by mlesikov** [comment]
I would like to see an examples: 
- binding as provider 
- binding as singleton provider

**Comment by kristiyanpetkov** [comment]
@mlesikov , i made an example with singleton provider. The difference between provider and singleton provider would be only the `.in(Singleton.class)` in the binding module .

**Comment by panayotkulchev** [comment]
The thinks I saw for this task on Kristiyan computer is enought to give LGTM for this task.

**Pull request merged**
